name: bcrypt-tool
base: core20
version: 'v1.1.1'
summary: bcrypt-tool is a dandy CLI tool for generating and matching bcrypt hashes
description: |
 bcrypt-tool is a dandy CLI tool for generating and matching bcrypt hashes

grade: stable
confinement: strict
architectures:
  - build-on: amd64

apps:
  bcrypt-tool:
    command: bin/bcrypt-tool

parts:
  bcrypt-tool:
    plugin: go
    go-channel: 1.16/stable
    source: https://github.com/shoenig/bcrypt-tool
    source-type: git
    source-tag: v1.1.1
    build-packages:
      - git
